# Generated by Django 5.0 on 2023-12-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Desc', models.CharField(max_length=20)),
                ('Year', models.IntegerField()),
                ('Image', models.ImageField(upload_to='app/cover,null=true,blank=true')),
            ],
        ),
    ]
