# Generated by Django 5.0 on 2024-01-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Year',
            new_name='year',
        ),
    ]
